version: "3.9"
services:
    backend:
        build: .
        environment:
            - DATABASE=search_nt_db
            - DB_USER=postgres
            - PASSWORD=postgres
            - DRIVER=postgresql+asyncpg
            - HOST=postgresdb
            - PORT=5432
        command:
            -   uvicorn src.main:app --host 0.0.0.0 --port 8000
        depends_on:
            - postgresdb
        ports:
            - "8000:8000"

    postgresdb:
        image: bitnami/postgresql
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=search_nt_db
        ports:
            - "5433:5432"
