version: "3.9"
services:
    backend:
        container_name: fastapi
        build: .
        environment:
            - DATABASE=search_nt_db
            - DB_USER=postgres
            - PASSWORD=postgres
            - DRIVER=postgresql+asyncpg
            - HOST=postgresdb
            - PORT=5432
        command: ['python', 'src/main.py']
        depends_on:
            - postgresdb
        ports:
            - "8000:8000"

    postgresdb:
        image: bitnami/postgresql
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=search_nt_db
        expose:
            - 5432
#        ports:
#            - "5433:5432"
