version: "3.9"
services:
    backend:
        container_name: fastapi
        build: .
        environment:
            - REDIS_PASSWORD=redisson
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        command: ["./wait_for_it.sh", "redis:6379", "--", 'python', 'src/main.py']
        depends_on:
            - 'redis'
        restart: always
        ports:
            - "8000:8000"

    redis:
        image: redis
        environment:
            - REDIS_PASSWORD=redisson
            - REDIS_HOST=redis
            - REDIS_PORT=6380
        expose:
            - 6379
        restart: always
        ports:
            - "6380:6379"
