"""02_new_generation

Revision ID: 4480695c2610
Revises: eb92a0e6fd91
Create Date: 2023-04-26 17:01:29.850638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4480695c2610'
down_revision = 'eb92a0e6fd91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('symbol', sa.Column('stock_market', sa.String(length=30), nullable=True))
    op.add_column('symbol', sa.Column('price_precision', sa.Integer(), nullable=True))
    op.add_column('symbol', sa.Column('quantity_precision', sa.Integer(), nullable=True))
    op.drop_constraint('symbol_symbol_key', 'symbol', type_='unique')
    op.create_index('symbolindex', 'symbol', ['stock_market', 'symbol'], unique=True)
    op.drop_column('symbol', 'baseAsset')
    op.drop_column('symbol', 'quotePrecision')
    op.drop_column('symbol', 'liquidationFee')
    op.drop_column('symbol', 'settlePlan')
    op.drop_column('symbol', 'quantityPrecision')
    op.drop_column('symbol', 'quoteAsset')
    op.drop_column('symbol', 'maintMarginPercent')
    op.drop_column('symbol', 'triggerProtect')
    op.drop_column('symbol', 'requiredMarginPercent')
    op.drop_column('symbol', 'contractType')
    op.drop_column('symbol', 'onboardDate')
    op.drop_column('symbol', 'deliveryDate')
    op.drop_column('symbol', 'baseAssetPrecision')
    op.drop_column('symbol', 'marketTakeBound')
    op.drop_column('symbol', 'underlyingType')
    op.drop_column('symbol', 'marginAsset')
    op.drop_column('symbol', 'pricePrecision')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('symbol', sa.Column('pricePrecision', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('symbol', sa.Column('marginAsset', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('symbol', sa.Column('underlyingType', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('symbol', sa.Column('marketTakeBound', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('symbol', sa.Column('baseAssetPrecision', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('symbol', sa.Column('deliveryDate', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('symbol', sa.Column('onboardDate', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('symbol', sa.Column('contractType', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('symbol', sa.Column('requiredMarginPercent', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('symbol', sa.Column('triggerProtect', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('symbol', sa.Column('maintMarginPercent', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('symbol', sa.Column('quoteAsset', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('symbol', sa.Column('quantityPrecision', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('symbol', sa.Column('settlePlan', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('symbol', sa.Column('liquidationFee', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('symbol', sa.Column('quotePrecision', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('symbol', sa.Column('baseAsset', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_index('symbolindex', table_name='symbol')
    op.create_unique_constraint('symbol_symbol_key', 'symbol', ['symbol'])
    op.drop_column('symbol', 'quantity_precision')
    op.drop_column('symbol', 'price_precision')
    op.drop_column('symbol', 'stock_market')
    # ### end Alembic commands ###
