"""01_new_generation

Revision ID: eb92a0e6fd91
Revises: 
Create Date: 2023-04-23 19:49:46.582001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb92a0e6fd91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('binance_order',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('client_order_id', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=False),
    sa.Column('orig_qty', sa.Float(), nullable=False),
    sa.Column('executed_qty', sa.Float(), nullable=False),
    sa.Column('cum_qty', sa.Float(), nullable=False),
    sa.Column('cum_quote', sa.Float(), nullable=False),
    sa.Column('time_in_force', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('reduce_only', sa.Boolean(), nullable=False),
    sa.Column('close_position', sa.Boolean(), nullable=False),
    sa.Column('side', sa.String(length=50), nullable=False),
    sa.Column('position_side', sa.String(length=50), nullable=False),
    sa.Column('stop_price', sa.Float(), nullable=False),
    sa.Column('working_type', sa.String(length=50), nullable=False),
    sa.Column('price_protect', sa.Boolean(), nullable=False),
    sa.Column('orig_type', sa.String(length=50), nullable=False),
    sa.Column('update_time', sa.BigInteger(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('black_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_enable', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock_market', sa.String(length=50), nullable=False),
    sa.Column('signal_name', sa.String(length=100), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('lot', sa.Float(), nullable=False),
    sa.Column('first_order_lot', sa.Float(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('point', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_position_user_id'), 'position', ['user_id'], unique=False)
    op.create_index('posindex', 'position', ['user_id', 'strategy_id', 'symbol_id', 'signal_name', 'stock_market'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('permission', sa.JSON(), nullable=True),
    sa.Column('is_enable', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('lot', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('point', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_quantity', sa.Float(), nullable=False),
    sa.Column('lot_percent', sa.Float(), nullable=False),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('tp_margin', sa.Float(), nullable=False),
    sa.Column('tp_price', sa.Float(), nullable=False),
    sa.Column('tp_count', sa.Integer(), nullable=False),
    sa.Column('tp_enable', sa.Integer(), nullable=False),
    sa.Column('sl_margin', sa.Float(), nullable=False),
    sa.Column('sl_price', sa.Float(), nullable=False),
    sa.Column('sl_enable', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_tp_and_sl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=15), nullable=False),
    sa.Column('lot_volume', sa.Float(), nullable=False),
    sa.Column('price_by_margin', sa.Float(), nullable=False),
    sa.Column('price_by_price', sa.Float(), nullable=False),
    sa.Column('callback_rate', sa.Float(), nullable=False),
    sa.Column('bind', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_tp_and_sl_strategy_id'), 'strategy_tp_and_sl', ['strategy_id'], unique=False)
    op.create_table('symbol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_enable', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=True),
    sa.Column('pair', sa.String(length=30), nullable=True),
    sa.Column('contractType', sa.String(length=30), nullable=True),
    sa.Column('deliveryDate', sa.BigInteger(), nullable=True),
    sa.Column('onboardDate', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('marginAsset', sa.String(length=30), nullable=True),
    sa.Column('maintMarginPercent', sa.String(length=30), nullable=True),
    sa.Column('requiredMarginPercent', sa.String(length=30), nullable=True),
    sa.Column('baseAsset', sa.String(length=30), nullable=True),
    sa.Column('quoteAsset', sa.String(length=30), nullable=True),
    sa.Column('pricePrecision', sa.Integer(), nullable=True),
    sa.Column('quantityPrecision', sa.Integer(), nullable=True),
    sa.Column('baseAssetPrecision', sa.Integer(), nullable=True),
    sa.Column('quotePrecision', sa.Integer(), nullable=True),
    sa.Column('settlePlan', sa.BigInteger(), nullable=True),
    sa.Column('triggerProtect', sa.String(length=30), nullable=True),
    sa.Column('underlyingType', sa.String(length=30), nullable=True),
    sa.Column('liquidationFee', sa.String(length=30), nullable=True),
    sa.Column('marketTakeBound', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=300), nullable=True),
    sa.Column('first_name', sa.String(length=300), nullable=True),
    sa.Column('last_name', sa.String(length=400), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('telegram_chat_id', sa.Integer(), nullable=True),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_chat_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('user_account_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock_market', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('last_update_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock_market', sa.String(length=50), nullable=False),
    sa.Column('hashed_key', sa.String(length=1024), nullable=False),
    sa.Column('hashed_secret', sa.String(length=1024), nullable=False),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_enable', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_trade_strategy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('signal_name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('stock_market', sa.String(length=50), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lot_quantity', sa.Float(), nullable=False),
    sa.Column('lot_percent', sa.Float(), nullable=False),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('averaging', sa.Integer(), nullable=False),
    sa.Column('averaging_count', sa.Integer(), nullable=False),
    sa.Column('averaging_volume', sa.Integer(), nullable=False),
    sa.Column('tp_enable', sa.Integer(), nullable=False),
    sa.Column('sl_enable', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_trade_strategy_user_id'), 'user_trade_strategy', ['user_id'], unique=False)
    op.create_table('user_trading_status',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_trading_status')
    op.drop_index(op.f('ix_user_trade_strategy_user_id'), table_name='user_trade_strategy')
    op.drop_table('user_trade_strategy')
    op.drop_table('user_settings')
    op.drop_table('user_account_info')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('symbol')
    op.drop_index(op.f('ix_strategy_tp_and_sl_strategy_id'), table_name='strategy_tp_and_sl')
    op.drop_table('strategy_tp_and_sl')
    op.drop_table('strategy')
    op.drop_table('signal')
    op.drop_table('role')
    op.drop_index('posindex', table_name='position')
    op.drop_index(op.f('ix_position_user_id'), table_name='position')
    op.drop_table('position')
    op.drop_table('black_list')
    op.drop_table('binance_order')
    # ### end Alembic commands ###
