{'data': {'orderId': 25376574230,
          'symbol': 'MATICUSDT',
          'status': 'NEW',
          'clientOrderId': 'rl2JNRyG5kzs8MfaqSDbhi',
          'price': '0',
          'avgPrice': '0.00000',
          'origQty': '9',
          'executedQty': '0',
          'cumQty': '0',
          'cumQuote': '0',
          'timeInForce': 'GTC',
          'type': 'MARKET',
          'reduceOnly': False,
          'closePosition': False,
          'side': 'SELL',
          'positionSide': 'BOTH',
          'stopPrice': '0',
          'workingType': 'CONTRACT_PRICE',
          'priceProtect': False,
          'origType': 'MARKET',
          'updateTime': 1681846667406}} # noqa
